# Generated by Django 3.1.7 on 2021-03-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('Ruto_Samoei', models.CharField(max_length=30)),
                ('Raila_Amolo', models.CharField(max_length=30)),
                ('Mudavadi_Musalia', models.CharField(max_length=30)),
                ('Gideon_Moi', models.CharField(max_length=30)),
                ('Kivutha_Kibwana', models.CharField(max_length=30)),
                ('Kituyi_Mukhisa', models.CharField(max_length=30)),
                ('Ruto_Samoei_count', models.IntegerField(default=0)),
                ('Raila_Amolo_count', models.IntegerField(default=0)),
                ('Mudavadi_Musalia_count', models.IntegerField(default=0)),
                ('Gideon_Moi_count', models.IntegerField(default=0)),
                ('Kivutha_Kibwana_count', models.IntegerField(default=0)),
                ('Kituyi_Mukhisa_count', models.IntegerField(default=0)),
            ],
        ),
    ]
