# Generated by Django 3.1.7 on 2021-03-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='poll_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ruto_Samoei_count', models.IntegerField(default=0)),
                ('Raila_Amolo_count', models.IntegerField(default=0)),
                ('Mudavadi_Musalia_count', models.IntegerField(default=0)),
                ('Gideon_Moi_count', models.IntegerField(default=0)),
                ('Kivutha_Kibwana_count', models.IntegerField(default=0)),
                ('Kituyi_Mukhisa_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='poll',
            name='Gideon_Moi_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='Kituyi_Mukhisa_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='Kivutha_Kibwana_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='Mudavadi_Musalia_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='Raila_Amolo_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='Ruto_Samoei_count',
        ),
    ]
