# Generated by Django 3.1.7 on 2021-03-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['president']},
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='Gideon_Moi',
            new_name='political_party',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='Gideon_Moi_count',
            new_name='poll_number',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='Kituyi_Mukhisa',
            new_name='president',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='Kituyi_Mukhisa_count',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='Kivutha_Kibwana',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='Kivutha_Kibwana_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='Mudavadi_Musalia',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='Mudavadi_Musalia_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='Raila_Amolo',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='Raila_Amolo_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='Ruto_Samoei',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='Ruto_Samoei_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='question',
        ),
    ]
